export const products = [
  {
    brandName: 'doubleEdited',
    productId: 10,
    productName: 'hamburguer',
    SKU: 'ajshdasdjhgvas564da7sd6r',
    price: 6.99,
    status: 'active',
    internalName: 'hamburguer modified',
    displayName: 'hamburguer modified',
    description: 'lorem ipsum hamburguer',
    id: 11,
    name: 'Example Driver',
    active: 'true',
    type: 'notification',
    integration: 'example',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 11,
    productName: 'Bacon Cheeseburger',
    SKU: 'jbmnsdbvsjdhfg76534kjsdf',
    price: 8.99,
    status: 'inactive',
    internalName: 'Bacon modified',
    displayName: 'Bacon modified',
    description: 'lorem ipsum Bacon',
    id: 12,
    name: 'Cristian Test',
    active: 'true',
    type: 'notification',
    integration: 'doordash_drive',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 12,
    productName: 'Cowboy Burger',
    SKU: 'mnblkajsy6ytqj323js3r3jb',
    price: 6.99,
    status: 'active',
    internalName: 'Cowboy modified',
    displayName: 'Cowboy modified',
    description: 'lorem ipsum Cowboy',
    id: 13,
    name: 'Cristian test 2',
    active: 'true',
    type: 'notification',
    integration: 'twili_sms',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 13,
    productName: 'Itallian Special',
    SKU: 'msdfbsjdhfglkjas9893bja6',
    price: 6.99,
    status: 'active',
    internalName: 'Itallian modified',
    displayName: 'Itallian modified',
    description: 'lorem ipsum Itallian',
    id: 14,
    name: 'tests sedgrid',
    active: 'false',
    type: 'delivery',
    integration: 'example 1',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 14,
    productName: 'Buffalo Chicken',
    SKU: 'a,nmbsmnabsddkqjuyyqe223',
    price: 4.99,
    status: 'active',
    internalName: 'Buffalo modified',
    displayName: 'Buffalo modified',
    description: 'lorem ipsum Buffalo',
    id: 15,
    name: 'test cristian twilio sms',
    active: 'false',
    type: 'delivery',
    integration: 'doordash_drive',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 15,
    productName: 'Chicken Salad',
    SKU: 'lalaksjshte23us8basgasd3',
    price: 2.99,
    status: 'active',
    internalName: 'Chicken modified',
    displayName: 'Chicken modified',
    description: 'lorem ipsum Chicken',
    id: 16,
    name: 'Grubhub order',
    active: 'true',
    type: 'notification',
    integration: 'twilio_sms',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 16,
    productName: 'Wing Combos',
    SKU: 'asd3215asdnnusd8adhafag8',
    price: 3.99,
    status: 'active',
    internalName: 'Wing modified',
    displayName: 'Wing modified',
    description: 'lorem ipsum Wing',
    id: 17,
    name: 'Example Doordash',
    active: 'false',
    type: 'delivery',
    integration: 'grubhub',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 17,
    productName: '10 Wings',
    SKU: 'nd342567aerewquyeopnashd',
    price: 9.99,
    status: 'active',
    internalName: '10 Wings modified',
    displayName: '10 Wings modified',
    description: 'lorem ipsum 10 Wings',
    id: 18,
    name: 'Ovation',
    active: 'false',
    type: 'delivery',
    integration: 'doordash_drive',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 18,
    productName: 'Small Cake',
    SKU: 'asdmfbj83e4efjksgdf32hsd',
    price: 7.99,
    status: 'active',
    internalName: 'Small Cake modified',
    displayName: 'Small Cake modified',
    description: 'lorem ipsum Small Cake',
    id: 19,
    name: 'Twilio SMS',
    active: 'true',
    type: 'notification',
    integration: 'ovation_notification',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 19,
    productName: 'Coke',
    SKU: 'asmndvashgcfd365saas55as',
    price: 9.99,
    status: 'active',
    internalName: 'Coke modified',
    displayName: 'Coke modified',
    description: 'lorem ipsum Coke',
    id: 20,
    name: 'Sendgrid Email',
    active: 'true',
    type: 'delivery',
    integration: 'twilio_sms',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 20,
    productName: 'hamburguer rice',
    SKU: 'ajshdasdjhgvas564da7sd6r',
    price: 6.99,
    status: 'active',
    internalName: 'hamburguer rice modified',
    displayName: 'hamburguer rice modified',
    description: 'lorem ipsum hamburguer rice',
    id: 21,
    name: 'test 123',
    active: 'true',
    type:  'notification',
    integration: 'doordash_drive',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 21,
    productName: 'Cucayo Cheeseburger',
    SKU: 'jbmnsdbvsjdhfg76534kjsdf',
    price: 8.99,
    status: 'active',
    internalName: 'Cucayo Cheeseburger modified',
    displayName: 'Cucayo Cheeseburger modified',
    description: 'lorem ipsum Cucayo Cheeseburger',
    id: 22,
    name: 'Email Scrapper',
    active: 'true',
    type:  'notification',
    integration: 'sendgrid_email_notification',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 22,
    productName: '"Cowboys from hell" Burger',
    SKU: 'mnblkajsy6ytqj323js3r3jb',
    price: 6.99,
    status: 'active',
    internalName: '"Cowboys from hell" Burger modified',
    displayName: '"Cowboys from hell" Burger modified',
    description: 'lorem ipsum "Cowboys from hell" Burger',
    id: 23,
    name: 'EXAMPLE',
    active: 'false',
    type: 'notification',
    integration: 'email_scraper_orders',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 23,
    productName: 'Itallian "rocky" Special',
    SKU: 'msdfbsjdhfglkjas9893bja6',
    price: 6.99,
    status: 'active',
    internalName: 'Itallian "rocky" Special modified',
    displayName: 'Itallian "rocky" Special modified',
    description: 'lorem ipsum Itallian "rocky" Special',
    id: 24,
    name: 'Marketman',
    active: 'false',
    type: 'delivery',
    integration: 'doordash_drive_test_2',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 24,
    productName: 'Buffalo Grill',
    SKU: 'a,nmbsmnabsddkqjuyyqe223',
    price: 4.99,
    status: 'active',
    internalName: 'Buffalo Grill modified',
    displayName: 'Buffalo Grill modified',
    description: 'lorem ipsum  Buffalo Grill',
    id: 25,
    name: 'Test 3',
    active: 'true',
    type: 'delivery',
    integration: 'doordash_drive_test_3',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 25,
    productName: 'Chicken and pork Salad',
    SKU: 'lalaksjshte23us8basgasd3',
    price: 2.99,
    status: 'active',
    internalName: 'Chicken and pork Salad modified',
    displayName: 'Chicken and pork Salad modified',
    description: 'lorem ipsum Chicken and pork Salad',
    id: 26,
    name: 'Test 1',
    active: 'false',
    type: 'notification',
    integration: 'text_1_notification',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 26,
    productName: 'Legs Combos',
    SKU: 'asd3215asdnnusd8adhafag8',
    price: 3.99,
    status: 'active',
    internalName: 'Legs Combos modified',
    displayName: 'Legs Combos modified',
    description: 'lorem ipsum Legs Combos',
    id: 27,
    name: 'Test 2',
    active: 'true',
    type: 'notification',
    integration: 'test_2_notification',
    edit: '',
  },
  {
    brandName: 'doubleEdited',
    productId: 27,
    productName: '100 Wings',
    SKU: 'nd342567aerewquyeopnashd',
    price: 9.99,
    status: 'active',
    internalName: '100 Wings modified',
    displayName: '100 Wings modified',
    description: 'lorem ipsum 100 Wings',
    id: 28,
    name: 'Tests 4',
    active: 'true',
    type: 'delivery',
    integration: 'test_4_example',
    edit: '',
  },
  {
    brandName: 'edited',
    productId: 28,
    productName: 'Biggie Small Cake',
    SKU: 'asdmfbj83e4efjksgdf32hsd',
    price: 7.99,
    status: 'active',
    internalName: 'Biggie Small Cake modified',
    displayName: 'Biggie Small Cake modified',
    description: 'lorem ipsum Biggie Small Cake',
    id: 29,
    name: 'Test 5',
    active: 'false',
    type: 'delivery',
    integration: 'test_5_example',
    edit: '',

  },
  {
    brandName: 'doubleEdited',
    productId: 29,
    productName: 'Coke roach soda',
    SKU: 'asmndvashgcfd365saas55as',
    price: 9.99,
    status: 'active',
    internalName: 'Coke roach soda modified',
    displayName: 'Coke roach soda modified',
    description: 'lorem ipsum  Coke roach soda',
    id: 30,
    name: 'Test 6',
    active: 'false',
    type: 'notification',
    integration: 'text_6_example',
    edit: '',
  },
];
